version: '3'
services:
#  client:
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    container_name: arter-client
#    command: npm run start
#    restart: unless-stopped
#    depends_on:
#      - mongo
#    networks:
#      - arter-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: arter-admin
    command: serve -s build -l 3001
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - arter-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: arter-api
    command: node ./dist/main.js
    restart: unless-stopped
    environment:
      - PORT=3002
      - MONGO_LOGIN=admin
      - MONGO_PASSWORD=admin
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_AUTHDATABASE=admin
      - JWT_SECRET=test
    depends_on:
      - mongo
    networks:
      - arter-network
    volumes:
      - ./uploads:/opt/app/uploads

  mongo:
    image: mongo:4.4.4
    container_name: arter-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-4.4:/data/db
    networks:
      - arter-network
    command: --wiredTigerCacheSizeGB 1.5

  nginx:
    image: nginx:stable-alpine
    container_name: arter-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/default.conf
      - ./uploads:/media/uploads
    depends_on:
      - admin
#      - client
      - api
    networks:
      - arter-network

volumes:
  mongodb_api:

networks:
  arter-network:
    driver: bridge
