import Head from 'next/head';
import { withLayout } from '../HOC/layout/Layout';
import cls from '../styles/Home.module.css';

function Home(): JSX.Element {
	return (
		<div className={cls.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<div>
				asdasdasd
			</div>
		</div>
	);
}

export default withLayout(Home);
