import { useRouter } from 'next/router';
import Head from 'next/head';
import { withLayout } from '../HOC/layout/Layout';
import cls from '../styles/Home.module.css';
import { GetStaticProps } from 'next';
import axios from 'axios';
import { API } from '../helpers/api';
import { PageInterface } from '../interfaces/HomePropsInterface';
import Image from 'next/image';
import { useContext } from 'react';
import { AppContext } from '../context/app.context';
import { useTranslation, withTranslation } from 'next-i18next';

function Home(): JSX.Element {
	const router = useRouter();
	const {page} = useContext(AppContext);
	const {t} = useTranslation();
	console.log(router);
	return (
		<>
			<Head>
				<title>{page.seo.seoTitle[router.locale as string]}</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<div>
				{t('page.index')}
				<Image
					src={`${API.host}/${page.slides[0].image}`}
					width={500}
					height={500}
				/>
			</div>
		</>
	);
}

export default withLayout(Home);

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
	const {data: page} = await axios.get<PageInterface>(`${API.host}/${API.page}`);
	return {
		props: {
			page
		}
	};
};

interface HomeProps extends Record<string, unknown>{
	page: PageInterface
}
